name: Build Docker Image for Apache Ignite

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Branch to use
        required: true
        type: string
        default: staging

      CLUSTER:
        description: Environment
        required: true
        type: choice
        default: staging
        options:
          - new-main-default
          - staging

      JAVA_VERSION:
        required: false
        type: string

      MAVEN_VERSION:
        required: false
        type: string

jobs:
  Deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout to branch
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.BRANCH }}

      - name: Build and Test
        uses: stacktome/actions/setup_scala@master
        with:
          JAVA_VERSION: ${{ inputs.JAVA_VERSION }}
          MAVEN_VERSION: ${{ inputs.MAVEN_VERSION }}

      - name: List
        id: list
        run: |
          mvn clean install -Pall-java,all-scala,licenses -DskipTests
          mvn initialize -Pjavadoc
          mvn initialize -Prelease
